import { MenuItem, Testimonial, Stat } from './types';

export const MENU_ITEMS: MenuItem[] = [
  // Main Dishes
  {
    id: 'm1',
    name: 'Pilau',
    description: 'Aromatic basmati rice slow-cooked with a blend of cloves, cardamom, and cinnamon, served with zesty kachumbari.',
    price: 180,
    category: 'Main Dish',
    isSpicy: true,
    image: 'https://images.unsplash.com/photo-1545243191-240179d67713?auto=format&fit=crop&q=80',
    rating: 4.8,
  },
  {
    id: 'm2',
    name: 'Ugali Beef',
    description: 'Traditional white maize meal served with tender cubes of beef slow-simmered in a rich, savory bone-broth gravy.',
    price: 200,
    category: 'Main Dish',
    image: 'https://images.unsplash.com/photo-1604329760662-4299b8296317?auto=format&fit=crop&q=80',
    rating: 4.5,
  },
  {
    id: 'm3',
    name: 'Rice Beef',
    description: 'Fluffy steamed rice paired with succulent beef chunks braised in a flavorful tomato and onion reduction.',
    price: 250,
    category: 'Main Dish',
    image: 'https://images.unsplash.com/photo-1512058560366-cd242d4536ee?auto=format&fit=crop&q=80',
  },
  {
    id: 'm4',
    name: 'Ugali Matumbo',
    description: 'Authentic tripe stew seasoned with local herbs, served with stone-ground white ugali for a true taste of tradition.',
    price: 180,
    category: 'Main Dish',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&q=80',
  },
  {
    id: 'm5',
    name: 'Ugali Fish (200g)',
    description: 'Petite Lake Victoria tilapia (200g) charcoal-grilled with a lemon-garlic infusion, served with traditional greens.',
    price: 200,
    category: 'Main Dish',
    image: 'https://images.unsplash.com/photo-1599084993091-1cb5c0721cc6?auto=format&fit=crop&q=80',
    isChefSpecial: true,
    rating: 4.9,
  },
  {
    id: 'm5_1',
    name: 'Ugali Fish (250g)',
    description: 'Medium-small Lake Victoria tilapia (250g) seasoned with our secret Lurambi rub and grilled over open embers.',
    price: 250,
    category: 'Main Dish',
    image: 'https://images.unsplash.com/photo-1599084993091-1cb5c0721cc6?auto=format&fit=crop&q=80',
    isChefSpecial: true,
  },
  {
    id: 'm6',
    name: 'Ugali Fish (300g)',
    description: 'Perfectly sized charcoal-grilled tilapia (300g) with a crispy skin and tender, juicy flesh, served with local sides.',
    price: 300,
    category: 'Main Dish',
    image: 'https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?auto=format&fit=crop&q=80',
    isChefSpecial: true,
    rating: 5.0,
  },
  {
    id: 'm6_1',
    name: 'Ugali Fish (350g)',
    description: 'Hearty 350g tilapia, marinated in cold-pressed oils and local spices, then expertly grilled to perfection.',
    price: 350,
    category: 'Main Dish',
    image: 'https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?auto=format&fit=crop&q=80',
    isChefSpecial: true,
  },
  {
    id: 'm7',
    name: 'Ugali Fish (400g)',
    description: 'Our signature large tilapia (400g), hand-selected for quality and grilled with a savory herb-butter glaze.',
    price: 400,
    category: 'Main Dish',
    image: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?auto=format&fit=crop&q=80',
    isChefSpecial: true,
    rating: 4.8,
  },
  {
    id: 'm7_1',
    name: 'Ugali Fish (450g)',
    description: 'Grand 450g tilapia, a showcase of lakeside fresh flavor, grilled with aromatic wood smoke for a deep finish.',
    price: 450,
    category: 'Main Dish',
    image: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?auto=format&fit=crop&q=80',
    isChefSpecial: true,
  },
  {
    id: 'm7_2',
    name: 'Ugali Fish (500g)',
    description: 'The ultimate jumbo 500g tilapia, basted in a rich garlic-ginger sauce and grilled until flaky and delicious.',
    price: 500,
    category: 'Main Dish',
    image: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?auto=format&fit=crop&q=80',
    isChefSpecial: true,
  },
  {
    id: 'm8',
    name: 'Ugali Kuku',
    description: 'Savory organic chicken wet-fried with sweet bell peppers and onions, served with a generous portion of ugali.',
    price: 400,
    category: 'Main Dish',
    image: 'https://images.unsplash.com/photo-1606787366850-de63d05c6d96?auto=format&fit=crop&q=80',
  },
  {
    id: 'm9',
    name: 'Githeri',
    description: 'Nutritious corn and bean stew simmered with garden vegetables for a comforting, wholesome Kenyan staple.',
    price: 100,
    category: 'Main Dish',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&q=80',
  },
  {
    id: 'm10',
    name: 'Ugali Managu',
    description: 'Traditional nightshade greens sautéed with cream and local onions, served alongside our signature stone-ground ugali.',
    price: 120,
    category: 'Main Dish',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80',
  },
  {
    id: 'm11',
    name: 'Ugali Mayai',
    description: 'Farm-fresh eggs whisked with a touch of chili and tomato, fried to fluffy perfection and served with warm ugali.',
    price: 150,
    category: 'Main Dish',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80',
  },

  // Drinks
  {
    id: 'd1',
    name: 'Fresh Passion Juice',
    description: 'Chilled passion fruit nectar, freshly squeezed and bursting with tropical citrus notes and natural sweetness.',
    price: 100,
    category: 'Drink',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80',
  },
  {
    id: 'd2',
    name: 'Mango Juice',
    description: 'Velvety, sun-ripened mangoes blended into a thick, refreshing juice that tastes like Kenyan sunshine.',
    price: 100,
    category: 'Drink',
    image: 'https://images.unsplash.com/photo-1546173159-315724a9369b?auto=format&fit=crop&q=80',
  },
  {
    id: 'd6',
    name: 'Vanilla Milkshake',
    description: 'Premium vanilla bean ice cream blended into a silky smooth shake, topped with a dash of fresh cream.',
    price: 250,
    category: 'Drink',
    image: 'https://images.unsplash.com/photo-1572490122747-3cd68fbe5da1?auto=format&fit=crop&q=80',
    rating: 4.7,
  },
  {
    id: 'd7',
    name: 'Chocolate Milkshake',
    description: 'Decadent dark chocolate cocoa blended with cold milk for a rich, indulgent treat for chocolate lovers.',
    price: 250,
    category: 'Drink',
    image: 'https://images.unsplash.com/photo-1572490122747-3cd68fbe5da1?auto=format&fit=crop&q=80',
  },
  {
    id: 'd8',
    name: 'Ice Cream (Assorted)',
    description: 'Three scoops of premium ice cream (Vanilla, Strawberry, or Chocolate).',
    price: 200,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1563805042-7684c849a158?auto=format&fit=crop&q=80',
  },
  {
    id: 'd3',
    name: 'Minute Maid',
    description: 'Bottle of premium fruit juice.',
    price: 100,
    category: 'Drink',
    image: 'https://images.unsplash.com/photo-1622597467825-f828a5044434?auto=format&fit=crop&q=80',
  },
  {
    id: 'd4',
    name: 'Dasani Water',
    description: 'Pure, chilled mineral water.',
    price: 50,
    category: 'Drink',
    image: 'https://images.unsplash.com/photo-1516733725897-1aa73b87c8e8?auto=format&fit=crop&q=80',
  },
  {
    id: 'd5',
    name: 'Soda (300ml)',
    description: 'Chilled selection of your favorite sodas.',
    price: 50,
    category: 'Drink',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80',
  },

  // Breakfast
  {
    id: 'b1',
    name: 'Mixed Tea',
    description: 'A classic breakfast tea brewed from the finest Kenyan tea leaves and combined with rich, whole milk.',
    price: 50,
    category: 'Breakfast',
    image: 'https://images.unsplash.com/photo-1544787210-282aa518d7f3?auto=format&fit=crop&q=80',
  },
  {
    id: 'b2',
    name: 'White Tea',
    description: 'Creamy and warming milk tea infused with hand-grated fresh ginger for a spicy, comforting kick.',
    price: 50,
    category: 'Breakfast',
    image: 'https://images.unsplash.com/photo-1556040220-4096d53b47bf?auto=format&fit=crop&q=80',
  },
  {
    id: 'b3',
    name: 'Lemon Tea',
    description: 'Black tea infused with the bright, citrusy zing of freshly squeezed lemons. A revitalizing way to start your day.',
    price: 40,
    category: 'Breakfast',
    image: 'https://images.unsplash.com/photo-1563148154-201620c4c47f?auto=format&fit=crop&q=80',
  },

  // Snacks
  {
    id: 's1',
    name: 'Sausage',
    description: 'Premium beef sausage, lightly seasoned and grilled until the casing snaps to reveal a juicy, flavorful center.',
    price: 50,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1532245104268-6bc447c1a6d5?auto=format&fit=crop&q=80',
  },
  {
    id: 's2',
    name: 'Samosa',
    description: 'Hand-folded golden triangles filled with lean minced meat and a secret blend of spicy Kenyan herbs.',
    price: 60,
    category: 'Snacks',
    isSpicy: true,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb1ce24?auto=format&fit=crop&q=80',
  },
  {
    id: 's3',
    name: 'Chips',
    description: 'Hand-cut local potatoes, twice-fried to achieve a perfectly crispy golden exterior and fluffy interior.',
    price: 150,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?auto=format&fit=crop&q=80',
  },
  {
    id: 's4',
    name: 'Spanish Omelette',
    description: 'Whisked farm eggs pan-seared with finely diced onions, bell peppers, and juicy tomatoes for a vibrant taste.',
    price: 100,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1510629954389-c1e0da47d4ec?auto=format&fit=crop&q=80',
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Brian Omondi',
    role: 'Regular Diner',
    content: 'The best fish in Western Kenya. The ambiance is world-class and the service is impeccable.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80',
  },
  {
    id: '2',
    name: 'Sarah Wanjiku',
    role: 'Food Blogger',
    content: 'Lurambi Fish Grill brings a touch of luxury to Kakamega. The Whole Tilapia is a masterpiece.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80',
  },
  {
    id: '3',
    name: 'John Musyoka',
    role: 'Business Consultant',
    content: 'The perfect spot for client meetings. Quiet, elegant, and the food is consistently outstanding.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80',
  },
  {
    id: '4',
    name: 'Amina Hassan',
    role: 'Local Resident',
    content: 'Finally, a place in Lurambi that understands both tradition and luxury. Their Pilau is the best in town.',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&q=80',
  }
];

export const STATS: Stat[] = [
  { label: 'Happy Customers', value: '25k+', icon: 'Users' },
  { label: 'Fish Served', value: '18k+', icon: 'Fish' },
  { label: 'Chef Awards', value: '12', icon: 'Star' }
];

export const ADMIN_EMAIL = 'lurambifishgrillKE@gmail.com';
export const WHATSAPP_LINK = 'https://wa.me/254794532900?text=Hello%20Lurambi%20Fish%20Grill,%20I\'d%20like%20to%20place%20an%20order.';
